const GET_PRODUCTS = 'GET_PRODUCTS';
const ADD_PRODUCT = 'ADD_PRODUCT';
const EDIT_PRODUCT = 'EDIT_PRODUCT';
const DELETE_PRODUCT = 'DELETE_PRODUCT';

export {GET_PRODUCTS, DELETE_PRODUCT, EDIT_PRODUCT, ADD_PRODUCT}
